### ISSUE TITLE
Applications Freeze

### ISSUE THREAD

**Issue by mquarneti** [KaizIqbal/Bibata_Cursor#11]
v0.4.1, Ice variant, Arch Linux, Gnome 3.28.2
When I set the cursor, gnome tweaks freezes and the applications refuse to open (even gnome settings). Firefox seems to run OK.

**Comment by KaizIqbal** [comment]
I Faced this Problem.
I solved By remove `Inherits=Bibata_Oil`
in Your Flavour index.theme file 

Example (If You Use Bibata_Ice and install as root)
     `sudo nano /usr/share/icons/Bibata_Ice/index.theme `

**Comment by mquarneti** [comment]
it works now, thanks
