### ISSUE TITLE
Resize cursor is misaligned

### ISSUE THREAD

**Issue by deathtrip** [KaizIqbal/Bibata_Cursor#12]
When trying to resize a window or webpage element, the resize cursor triggers too early and is aligned not to the center dot but to the side arrow of whatever side the cursor was moving from.

![screenshot_20180706_182341](https://user-images.githubusercontent.com/8403455/42389736-eaf9463e-8149-11e8-8215-b22277f9f207.jpg)

**Comment by deathtrip** [comment]
I use size 28. It only appears to be affecting this size of all three variants of the cursor. Other sizes seem to be ok, haven't tested them all though.

**Comment by KaizIqbal** [comment]
i fix it.
Try It and Let Me Know.

**Comment by deathtrip** [comment]
Just tested it and everything seems alright. Thanks for fixing it. Keep up the good work.

**Comment by commonsourcecs** [comment]
Same/Similar/Recurring issue. 
Edges are hard to grasp and picture, but alignment seems odd once you get it too: 
Ex:
![ex1](https://user-images.githubusercontent.com/20587163/43863523-d2ad2316-9b11-11e8-89b6-f700f426f19c.png) ![ex2](https://user-images.githubusercontent.com/20587163/43863528-d6d26b04-9b11-11e8-924d-8f740702db1f.png)

**Comment by KaizIqbal** [comment]
Which size you Use??

**Comment by commonsourcecs** [comment]
Seems to be all of them, though mainly looked at 
Auto,24,28,32

**Comment by KaizIqbal** [comment]
**Fixed** 
You Direct Test Cursor By,Downloading  Package I attached link below :point_down: 
Any other **issues**,I am ready for _help_

[opendesktop](https://www.opendesktop.org/p/1197198/)

**Comment by commonsourcecs** [comment]
Much better. :+1:
