### ISSUE TITLE
Cursor w-resize is flickering

### ISSUE THREAD

**Issue by Etamuk** [KaizIqbal/Bibata_Cursor#13]
**Describe the bug**
The cursor for resizing the left border of an window (f.e. nemo) is flickering when the cursor changes from normal cursor to w-resize. The other resizing cursors are working fine.

**To Reproduce**
Set Bibata cursor 
You can check it on this site: http://www.echoecho.com/csscursors.htm
Go to TEST for w-resize
Now you can see it flickering

This happens to all cursor themes Oil, Ice and Amber

 - OS: Manjaro 17.1.12 with Cinnamon 3.8.8

**Comment by commonsourcecs** [comment]
Pull request opened with fix.
Reference from Manjaro Forum: https://forum.manjaro.org/t/new-cursor-theme-bibata-adaptabreath/54363/28
