### ISSUE TITLE
Original-Ice produces lots of warnings in my logs

### ISSUE THREAD

**Issue by binarykitchen** [KaizIqbal/Bibata_Cursor#167]
Hi, thanks for the cool icons,

Afraid, I'm seeing lots of noise in the logs like these:
```bash
$ gnome-control-center
12:05:40.5255                  Gtk[50554]: WARNING: Theme file for Bibata-Original-Ice has no directories
12:05:40.6111                  Gtk[50554]: WARNING: Theme file for Bibata-Original-Ice has no directories
```
Can we do something about this?

**Comment by stanio** [comment]
@binarykitchen, does adding a line:

```ini
Directories=
```

to the `index.theme` solve the issue?

**Comment by binarykitchen** [comment]
Ummm thanks @stanio but I can't find that file on my system.

**Comment by stanio** [comment]
It should be present in each theme directory, for example:

```
~/.local/share/icons/Bibata-Modern-Ice/index.theme
```

**Comment by binarykitchen** [comment]
Afraid no:
![image](https://github.com/ful1e5/Bibata_Cursor/assets/177641/de0a3493-5a7f-4507-aaa7-e21dbc88f085)

And I still have them activated and working fine. Weird:
![image](https://github.com/ful1e5/Bibata_Cursor/assets/177641/5a619289-0971-47a5-a5ea-3c5bb4980ba5)

**Comment by stanio** [comment]
And in the legacy location?

```
~/.icons/Bibata...
```

For all users?

```
/usr/share/icons/Bibata...
```

See the project [README](https://github.com/ful1e5/Bibata_Cursor?tab=readme-ov-file#installing-bibata-cursor), also.

**Comment by binarykitchen** [comment]
Ah, it's there:
![image](https://github.com/ful1e5/Bibata_Cursor/assets/177641/ef39d182-900b-45d3-99b9-4713e563267c)

And the contents were:
```
[Icon Theme]
Name=Bibata-Modern-Ice
Comment=White and rounded edge Bibata (v2.0.6). XCursors
Inherits="hicolor"
```

Just vim-added:
```
Directories=
```

Rebooting my machine. Will check further ...

**Comment by binarykitchen** [comment]
Yup, that fixed it 

Want me to do a PR, or you're going to add this in the next release?

**Comment by stanio** [comment]
I don't really maintain this project.  I've asked to verify this is the right solution to apply to a build tool of mine.  Hope it is useful for the maintainer of this project, also.

**Comment by binarykitchen** [comment]
All good, much respekt. Thanks for your input.
