### ISSUE TITLE
Add preview graphic of cursors

### ISSUE THREAD

**Issue by polarathene** [KaizIqbal/Bibata_Cursor#23]
You have nice big images that show one cursor state, but it's not clear without installing what the rest look like. Especially so at the [KDE store page](https://store.kde.org/p/1197198/) where it's common to get a preview of the set.

**Comment by deathtrip** [comment]
I agree. Currently even the one cursor state is barely visible, as the background is the same color as the cursor.

**Comment by ivanaugustobd** [comment]
To be honest, before see this I didn't even noticed that the cursor was there 😦

**Comment by KaizIqbal** [comment]
Cursor preview added to [**README.md**](https://github.com/KaizIqbal/Bibata_Cursor/blob/devlopment/README.md#preview) and also at **[KDE Store Page](https://store.kde.org/p/1197198/)** .
Thanks for be patient 🙃
