### ISSUE TITLE
[WINDOWS 10] Need to add new type

### ISSUE THREAD

**Issue by vonsogt** [KaizIqbal/Bibata_Cursor#30]
So, windows 10 have new cursor type:
- Location Select
- Person Select

Please we need this to get 1 pack of cursor

**Comment by Silicasandwhich** [comment]
I'll work on it, but for now I just use the basic select cursor. I'm also planning on speeding up the wait and progress cursors, so I'll probably roll out the new cursors when I do that.

**Comment by vonsogt** [comment]
Thanks
