### ISSUE TITLE
Add bibata cursor translucent to the "looking for another bibata?" section of README

### ISSUE THREAD

**Issue by Silicasandwhich** [KaizIqbal/Bibata_Cursor#35]
Since the translucent cursor set is finished, I think it should be added to the "looking for another bibata?" section of the README. If you don't want to recognize it as an official set, that's all good, just letting you know it's ready.

**Comment by KaizIqbal** [comment]
**Added** to README.md

**Comment by Silicasandwhich** [comment]
alright. thank you
