### ISSUE TITLE
Bibata Oil - Crosshair Alternative

### ISSUE THREAD

**Issue by proxeIO** [KaizIqbal/Bibata_Cursor#4]
Alternative Crosshair, the original could often visually get in the way when making finer adjustments

[crosshair.zip](https://github.com/KaizIqbal/Bibata_Cursor/files/1733888/crosshair.zip)

![image](https://user-images.githubusercontent.com/13005588/36343516-d96f3a8e-13d2-11e8-8ec5-56b1b0dc91d2.png)

**Note** - The file above contains a GIMP exported x11, no svg, I made this with very little effort and I am leaving here as a suggestion. Thanks for this awesome cursor set.

**Comment by proxeIO** [comment]
I'm glad you like it!

**Comment by KaizIqbal** [comment]
:smile: :+1:
