### ISSUE TITLE
[win] animations not smooth

### ISSUE THREAD

**Issue by GoncaloHit** [KaizIqbal/Bibata_Cursor#45]
**Describe the bug**
I have been using bibata oil for sometime, today i upgraded to the new cursor style, but the .anim cursors animations are not smooth, looks like the loading animation is 2fps.

**OS**
Windows 1909 build 18363 (latest Nov update)

**Comment by KaizIqbal** [comment]
I set **delay 20=>40** as default.You download binary on **[release page](https://github.com/KaizIqbal/Bibata_Cursor/releases)**.
Let me know it's working!

**Comment by gsbhasin123** [comment]
Whoa, great!

**Comment by GoncaloHit** [comment]
Maybe it is what it is, in the previous version, it was smooth like 60fps, tried latest version looks the same.
