### ISSUE TITLE
There is a "dirty" pixel in the cursor

### ISSUE THREAD

**Issue by Etamuk** [KaizIqbal/Bibata_Cursor#46]
Hello KAIZ!

I've downloaded Bibata_Classic and Bibata_Ice versions v0.4.2.alpha.1 and I noticed a wrong pixel in the cursors. 
Please see my both screenshots. 
Thank you for this great cursor themes. You did a good job :-)

![Bildschirmfoto vom 2019-11-26 20-10-50](https://user-images.githubusercontent.com/20098065/69665246-49ecac00-108a-11ea-930b-4438c2dff9b2.png)
![Bildschirmfoto vom 2019-11-26 20-14-45](https://user-images.githubusercontent.com/20098065/69665247-49ecac00-108a-11ea-9493-3c15c745126c.png)

**Comment by KaizIqbal** [comment]
Fixed Check [v0.4.2.alpha.2](https://github.com/KaizIqbal/Bibata_Cursor/releases/tag/v0.4.2.alpha.2).
