### ISSUE TITLE
same names in Oil and Classic

### ISSUE THREAD

**Issue by B1tl0rd** [KaizIqbal/Bibata_Cursor#48]
Please change the name and enter the correct one. index.theme cursor.theme

**Bibata Classic**
index.theme
[Icon Theme]
Name=Bibata Oil

**Bibata Oil**
index.theme
[Icon Theme]
Name=Bibata Oil

**Comment by KaizIqbal** [comment]
Holy Smoke i done it!
Now Corrected :+1:

**Comment by wcasanova** [comment]
last release same problem xD.
Bibata_KDE_Package.zip
https://github.com/KaizIqbal/Bibata_Cursor/releases/tag/v0.4.2
