### ISSUE TITLE
Pip dependency

### ISSUE THREAD

**Issue by Shatur95** [KaizIqbal/Bibata_Cursor#50]
**Is your feature request related to a problem? Please describe.**
Build script requires installation of `pip` to install [python-willow](https://www.archlinux.org/packages/community/x86_64/python-pillow/) that exists in ArchLinux repo. So I need to install pip even if I already have this dependency installed.

**Describe the solution you'd like**
It would be nice to remove `pip` requirement from build script.

**Comment by KaizIqbal** [comment]
I added **python-pillow** in build script,you find latest code on [development](https://github.com/KaizIqbal/Bibata_Cursor/tree/devlopment) branch.It is automatically skip pip requirements part if **Pillow** is installed on system. 😌

Let me know!

**Comment by Shatur95** [comment]
Thank you!
