### ISSUE TITLE
Compatibility with GNOME cursor sizes

### ISSUE THREAD

**Issue by alex285** [KaizIqbal/Bibata_Cursor#6]
nice theme! can you please add compatibility with GNOME Universal Access settings?

![pointer](https://user-images.githubusercontent.com/11244308/38453326-a916879c-3a5c-11e8-8923-8d8abdeba985.png)

**Comment by KaizIqbal** [comment]
I Update This Theme with in Resolution
   -24x24
   -28x28
   -32x32
   -48x48
And Fix Lot of Bug.Check it OUT!!!

**Comment by alex285** [comment]
@KaizIqbal  just did! this icon set is a very nice work!
i'm leaving the report open, because the two last sizes are missing!

**Comment by KaizIqbal** [comment]
Now I Added All Size. (24,28,32,48,56,64,72,80,88,96)

**Comment by alex285** [comment]
@KaizIqbal absolutely awesome! thank you!!
