### ISSUE TITLE
Can you port Bibata Cursor to Windows ?

### ISSUE THREAD

**Issue by 1612180** [KaizIqbal/Bibata_Cursor#7]
I love your cursor style, I use it on my Arch machine.
But my windows box doesn't have it. Can you port it for windows?

**Comment by KaizIqbal** [comment]
Yes Why not !!.
 First I make It Bug free After I Port It for Window

**Comment by thebigtoona** [comment]
I don't know a whole lot about windows, just a little powershell and basic use for gaming/work, and I would need to go looking around on a windows machine to see how easy/hard it would actually be.  This Q&A makes it sound farily easy though, (maybe some filetype changes, build path changes and rewrite of build/install scripts?) and the build script could just rewritten with powershell probably which is usable for anything xp on up I believe and comes standard in 8 on up I think but don't quote me on that lol.. 

https://answers.microsoft.com/en-us/windows/forum/windows_10-start-winpc/how-do-you-install-custom-cursors-in-windows-10/8dbc8d91-0dbe-4983-83e8-95ff8685c4bc

**Comment by Silicasandwhich** [comment]
I've made a pull request with windows cursor files. You'll have to manually apply them to your system, but that shouldn't be much of a problem
