### ISSUE TITLE
Corner cursor in GNOME inherits from Adwaita

### ISSUE THREAD

**Issue by alex285** [KaizIqbal/Bibata_Cursor#8]
A workaround is to edit
```
/usr/share/icons/default/index.theme 
```
You can notice the issue @ https://youtu.be/8zaJgi-u-Bg?t=29s

**Comment by KaizIqbal** [comment]
OK I will fix it.

**Comment by KaizIqbal** [comment]
I want time for it

**Comment by KaizIqbal** [comment]
Dear *Alex*,

Can you Expand your issue?,It will make me more clear what actual happen.

You able to share your
 ```/usr/share/icons/default/index.theme```

**Sorry** For Late answer 😖

**Comment by alex285** [comment]
hello @KaizIqbal no worries!

this is what i have done already. i have edited `/usr/share/icons/default/index.theme` to make it work properly. if there is not another way to fix it, feel free to close the issue, but it would be nice to add a note on README so people are aware of it!

**Comment by alex285** [comment]
hello @KaizIqbal i miss-read your question, so i removed my previous comment, sorry!

`/usr/share/icons/default/index.theme` was

```
[Icon Theme]
Inherits=Adwaita
```

edited to 
```
[Icon Theme]
Inherits=Bibata_Ice
```

**Comment by ArionWT** [comment]
@alex285, I think this is issue with Gnome Settings, which is not changed default XDG cursor specification file.
