### ISSUE TITLE
Incorrect placement of hotspot in i-beam cursor

### ISSUE THREAD

**Issue by mleyen** [KaizIqbal/Bibata_Cursor#9]
Hi,

The hotspot of the i-beam (text) cursor for all 3 variants is incorrectly placed at the bottom of the cursor for sizes 28 and 32, resulting in the cursor jumping around. The hotspot should be at the center.

I have version 0.4.1 from gnome-look.

Can you look into this?

Edit: did a pull request #10

**Comment by KaizIqbal** [comment]
Great Catcha I Update to OpenDesktop
